# Per-GP "signature volcano" view: each gene's normalized weight in a GP
# (x-axis, max |weight| = 1) vs. its mean shifted-log expression (y-axis),
# with the top |weight| genes labeled and dashed reference lines at
# +/- threshold.
#
# NOT originally from script/ or code/ -- these panels (Figure1.R panel 1D,
# Figure2.R panels 2D/2F/2H) are generated by the "immgen-signature" Shiny
# app (a sibling project at .../Immgen/webapps/immgen-signature/), which
# lives outside this repository. Ported here (from that app's
# R/mod_signature.R::.make_static_plot(), the version whose axis label
# exactly matches the published panels) so these 4 figure panels have
# working source code within this repo.
#
# The app lets a user interactively set n_label/threshold/bg_alpha per plot
# before exporting a PDF, so the exact values used for the published panels
# aren't recoverable from code alone -- defaults below match the app's own
# UI defaults (threshold = 0.1, n_label = 15, bg_alpha = 0.2) and should be
# adjusted to match the published panels if you know the values used.

# Max-|weight|-per-column normalization (matches the app's global.R::normalize_maxabs()).
normalize_maxabs <- function(mat) {
  apply(mat, 2, function(x) {
    nv <- max(abs(x), na.rm = TRUE)
    if (nv > 0) x / nv else x
  })
}

# Tidy per-GP data frame: Feature, Weight (normalized), MeanExpr, AbsWeight.
# Matches the app's global.R::get_signature_df() for type = "gene".
get_gp_signature_df <- function(gp, F_pm_normalized, mean_expr_vector) {
  common_genes <- intersect(rownames(F_pm_normalized), names(mean_expr_vector))
  data.frame(
    Feature = common_genes,
    Weight = as.numeric(F_pm_normalized[common_genes, gp]),
    MeanExpr = as.numeric(mean_expr_vector[common_genes]),
    AbsWeight = abs(as.numeric(F_pm_normalized[common_genes, gp])),
    stringsAsFactors = FALSE
  )
}

# Matches the app's R/mod_signature.R::.make_static_plot() exactly (axis
# label "Gene weight  (max|w|=1)", no "normalized" word -- the other,
# similarly-named plot_volcano_static() in the app's global.R uses a
# slightly different label and is NOT what the published panels use).
plot_gp_signature_volcano <- function(
  gp,
  F_pm_normalized,
  mean_expr_vector,
  threshold = 0.1,
  n_label = 15,
  bg_alpha = 0.2
) {
  df <- get_gp_signature_df(gp, F_pm_normalized, mean_expr_vector)
  df <- df[!is.na(df$MeanExpr), ]

  top_df <- df[order(-df$AbsWeight), ][seq_len(min(n_label, nrow(df))), ]
  bg_df <- df[!(df$Feature %in% top_df$Feature), ]

  ggplot2::ggplot() +
    ggplot2::geom_vline(xintercept = c(-threshold, threshold), linetype = "dashed", colour = "grey55", linewidth = 0.35) +
    scattermore::geom_scattermore(data = bg_df, ggplot2::aes(x = Weight, y = MeanExpr), pointsize = 2, alpha = bg_alpha, colour = "grey75") +
    ggplot2::geom_point(data = top_df, ggplot2::aes(x = Weight, y = MeanExpr), colour = "dodgerblue", size = 1.9, alpha = 0.9) +
    ggrepel::geom_text_repel(
      data = top_df, ggplot2::aes(x = Weight, y = MeanExpr, label = Feature),
      colour = "black", size = 3, segment.colour = "grey50",
      box.padding = 0.5, point.padding = 0.3, max.overlaps = Inf, min.segment.length = 0
    ) +
    ggplot2::labs(title = gp, x = "Gene weight  (max|w|=1)", y = "Mean shifted log expr") +
    ggplot2::theme_minimal(base_size = 11) +
    ggplot2::theme(panel.grid.minor = ggplot2::element_blank(), plot.title = ggplot2::element_text(face = "bold", hjust = 0.5, size = 12))
}
