# Figure 1. Overview.
#
# Panels produced (final files figures/final-selected/bits/Figure 1/1A.pdf .. 1I.pdf;
# no separate caption file was found for Figure 1 during this refactor):
#   1A  Global MDE colored by major lineage (subsampled per lineage).
#   1B  Hand-finished schematic (Adobe Illustrator) -- NOT code-generated,
#       no source to port. Not produced by this script.
#   1C  Gene-program network: 200 GPs linked by shared top signature genes.
#   1D  "Signature volcano" for GP1: each gene's normalized weight vs. mean
#       shifted-log expression, top genes labeled. NOT from the original
#       pre-refactor analysis code -- generated by the separate
#       "immgen-signature" Shiny app
#       (.../Immgen/webapps/immgen-signature/); see
#       code/R/volcano_helpers.R for the ported plotting function
#       and the caveat about n_label/threshold not being exactly recoverable.
#   1E  Histogram of the proportion of highly-active cells per GP.
#   1F  Histogram of the number of highly-active genes per GP.
#   1G  Boxplot of active-GP-count per cell, by major lineage.
#   1H  Boxplot of active-GP-count per cell, activated vs resting.
#   1I  Scatter of CD44 protein level vs. number of active GPs per cell.
# The original Figure_Overview.R produces 3 more outputs (raw
# active-cell-count histogram, active-gene proportion histogram, and a
# PVE-colored active-cell-vs-active-gene scatter) that don't match any
# remaining final-figure byte size -- saved under their descriptive names
# (not lettered) since they appear to not be part of the final 9-panel set.
#
# Source: ported from Figure_Overview.R (panels C, E-I) and
# Figure_Lineage.R's "MDE by Lineage" section (panel A, confirmed by
# an exact byte match between figures/final-selected/bits/Figure 1/1A.pdf
# and figures/Figure2_Lineage/UMAP_level1_group.pdf during this refactor).
#
# Required inputs (data/) -- see code/README.md's "Data provenance" table
# for the full picture:
#   flashier_snmf_summary.rds                [code/pipeline/01_extract_data.R]
#   L_pm_filtered.rds, F_pm_filtered.rds      [code/pipeline/01b_filter_cells.R]
#   igt1_96_..._ADTonly.Rds                   [primary input Seurat object]
#   protein_mat_normalized_lognorm.rds        [code/other/prepare_citeseq_protein_matrices_20260206.R]
#   umap_result.rds                           [gap, no producer script here]
#   mean_shifted_log_expr.rds                 [gap, no producer script here]
#   flashier_snmf_fitted_prior.rda            [gap, no producer script here]

library(ggplot2)
library(dplyr)
library(scattermore)
library(ComplexHeatmap)
library(circlize)
library(tibble)
library(Matrix) # protein_mat_normalized_lognorm is a dgCMatrix; must be
                # attached (not just loaded) for `[` subsetting to dispatch

data_path <- "data/"
figure_path <- "figures/generated/Figure 1/"
source("code/R/volcano_helpers.R") # plot_gp_signature_volcano() for panel 1D

# ============================================================
# Load data
# ============================================================
flashier_snmf_summary <- readRDS(paste0(data_path, "flashier_snmf_summary.rds"))
L_pm_filtered <- readRDS(paste0(data_path, "L_pm_filtered.rds"))
F_pm_filtered <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
seurat_meta <- readRDS(paste0(data_path, "igt1_96_withtotalvi20260206_clean_ADTonly.Rds"))@meta.data
seurat_meta_filtered <- seurat_meta[rownames(L_pm_filtered), ]
protein_mat_normalized_lognorm <- readRDS(paste0(data_path, "protein_mat_normalized_lognorm.rds"))
protein_mat_normalized_lognorm <- protein_mat_normalized_lognorm[rownames(L_pm_filtered), "CD44"]
mde_result <- readRDS(paste0(data_path, "umap_result.rds"))
colnames(mde_result) <- c("MDE_1", "MDE_2")
mde_result <- mde_result[rownames(L_pm_filtered), ]
df_mde <- as.data.frame(mde_result)

# ============================================================
# 1A: Global MDE colored by major lineage, subsampled per lineage
# ============================================================
set.seed(1)
df_mde_a <- df_mde %>% tibble::rownames_to_column("cellID")
plot_df <- df_mde_a %>%
  inner_join(seurat_meta_filtered %>% select(cellID, annotation_level1), by = "cellID") %>%
  filter(annotation_level1 != "thymocyte")
max_total <- 1000000
min_per_group <- 300
cap_per_group <- 20000
group_sizes <- plot_df %>% count(annotation_level1, name = "n")
G <- nrow(group_sizes)
base_per_group <- ceiling(max_total / max(G, 1))
sample_plan <- group_sizes %>% mutate(n_take = pmin(n, pmax(min_per_group, pmin(cap_per_group, base_per_group))))
plot_df_sub <- plot_df %>%
  group_by(annotation_level1) %>%
  group_modify(~ dplyr::slice_sample(.x, n = sample_plan$n_take[sample_plan$annotation_level1 == .y$annotation_level1])) %>%
  ungroup()

p_1A <- ggplot(plot_df_sub, aes(x = MDE_1, y = MDE_2)) +
  scattermore::geom_scattermore(aes(color = annotation_level1), pointsize = 1.2) +
  scale_color_manual(values = ZemmourLib::immgent_colors$level1) +
  coord_equal() +
  theme_classic() +
  labs(title = "MDE: Annotation Level 1", x = "MDE 1", y = "MDE 2", color = "Cell Type") +
  theme(legend.text = element_text(size = 10), legend.key.size = unit(1.5, "lines")) +
  guides(color = guide_legend(override.aes = list(size = 4)))
ggsave(filename = paste0(figure_path, "1A.pdf"), plot = p_1A, width = 5, height = 5)

# 1B: hand-finished Illustrator schematic -- not code-generated, no output here.

# Drop thymocytes from all downstream cell-level visualizations (matches
# Figure_Overview.R).
non_thymo_cells <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level1 != "thymocyte"]
L_pm_filtered <- L_pm_filtered[non_thymo_cells, ]
seurat_meta_filtered <- seurat_meta_filtered[non_thymo_cells, ]
protein_mat_normalized_lognorm <- protein_mat_normalized_lognorm[non_thymo_cells]

# ============================================================
# 1C: gene-program network -- the 200 GPs linked by their shared top signature
# genes, with a selected set of GPs highlighted. Each highlighted GP's color runs
# along its edges to its top signature genes (which are labeled); non-highlighted
# GPs are grey. Formal version: no legend / no GP-index labels -- the color->GP
# mapping and interpretation are in the Fig 1C caption (analysis/Figure1.Rmd).
# ============================================================
suppressPackageStartupMessages({
  library(igraph); library(tidygraph); library(ggraph)
})
N_TOP   <- 5                                      # top up-genes taken per GP
SIG_THR <- 0.1                                    # min per-GP-normalized loading
GP_HIGHLIGHTS <- c(                               # GP -> highlight color
  GP68  = "pink2",  GP58  = "orange2", GP35  = "purple", GP171 = "blue",
  GP1   = "cyan2",  GP56  = "red2",    GP161 = "brown",  GP6   = "green2",
  GP7   = "green3", GP196 = "yellow3")
GP_COL   <- "darkgrey"                            # non-highlighted GP nodes
GENE_COL <- "#C7A76C"                             # gene nodes (tan)

Fn <- F_pm_filtered
colnames(Fn) <- paste0("GP", seq_len(ncol(Fn)))
Fn <- sweep(Fn, 2, apply(abs(Fn), 2, max), "/")   # per-GP (column) max-abs norm
GPs <- colnames(Fn)

# each GP -> its top up-regulated signature genes (normalized loading >= SIG_THR)
top_up <- lapply(GPs, function(j) { x <- Fn[, j]
  u <- names(sort(x, decreasing = TRUE))[1:N_TOP]; u[x[u] >= SIG_THR] })
names(top_up) <- GPs
edges <- do.call(rbind, lapply(GPs, function(g)
  if (length(top_up[[g]])) data.frame(GP = g, Gene = top_up[[g]]) else NULL))

# bipartite GP<->gene graph (every GP + all its top genes); plain FR layout
gi <- graph_from_data_frame(edges, directed = FALSE)
g  <- as_tbl_graph(gi, directed = FALSE)
gp_set <- unique(edges$GP)
set.seed(1)
lay <- layout_with_fr(gi)
colnames(lay) <- c("x", "y"); rownames(lay) <- V(gi)$name
nm <- g %>% activate(nodes) %>% pull(name)

# highlight selected GPs: color their node + edges, label the genes they connect to
hl <- intersect(names(GP_HIGHLIGHTS), gp_set)
hl_genes <- setdiff(unique(unlist(
  lapply(hl, function(gp) neighbors(gi, gp)$name))), gp_set)
g <- g %>% activate(nodes) %>% mutate(
  is_gp = name %in% gp_set,
  gp_fill = ifelse(is_gp & name %in% hl, unname(GP_HIGHLIGHTS[name]), GP_COL),
  label_gene = !is_gp & name %in% hl_genes,
  gene_lab = ifelse(label_gene, name, ""),
  gp_size = ifelse(is_gp, 3, NA_real_))
g <- g %>% activate(edges) %>% mutate(
  gp_end = ifelse(.N()$is_gp[from], .N()$name[from], .N()$name[to]),
  gp_edge_highlight = gp_end %in% hl,
  gp_edge_col = ifelse(gp_edge_highlight, unname(GP_HIGHLIGHTS[gp_end]), NA_character_))

p_1C <- ggraph(g, layout = "manual", x = lay[nm, "x"], y = lay[nm, "y"]) +
  geom_edge_link(aes(filter = !gp_edge_highlight), color = "black", alpha = 0.18, width = 0.32) +
  geom_edge_link(aes(filter = gp_edge_highlight, edge_colour = gp_edge_col), alpha = 0.95, width = 1.25) +
  geom_node_point(aes(filter = !is_gp), shape = 16, size = 1, color = GENE_COL, alpha = 0.75) +
  geom_node_point(aes(filter = is_gp, size = gp_size, fill = gp_fill),
                  shape = 21, color = "white", stroke = 0.5) +
  geom_node_text(aes(filter = label_gene, label = gene_lab), repel = TRUE,
                 color = "black", size = 5, fontface = "italic", max.overlaps = Inf) +
  scale_fill_identity() + scale_edge_colour_identity() +
  scale_size_identity() + scale_edge_width_identity() +
  scale_x_continuous(expand = expansion(mult = 0.08)) +
  scale_y_continuous(expand = expansion(mult = 0.08)) +
  theme_void(base_size = 12) +
  theme(plot.margin = margin(10, 10, 10, 10), legend.position = "none")
ggsave(filename = paste0(figure_path, "1C.pdf"), plot = p_1C, width = 20, height = 20)

# ============================================================
# Candidates for 1D-1I: histograms of active-cell / active-gene counts
# (raw and proportion), boxplots of active-GP-count (activated vs resting;
# by lineage), CD44-vs-active-GP-count scatter, and the PVE-colored
# active-cell-vs-active-gene proportion scatter. 8 candidates, 6 final
# slots -- letters assigned by byte-size match against the ground truth
# during this refactor (see header note); unmatched two kept under their
# descriptive names.
# ============================================================
L_pm_norm_col <- L_pm_filtered / matrix(apply(L_pm_filtered, 2, function(x) max(x)), nrow = nrow(L_pm_filtered), ncol = ncol(L_pm_filtered), byrow = TRUE)
gp_active_cell_counts <- colSums((L_pm_norm_col) > 1e-1)

pdf(paste0(figure_path, "hist_active_cells_per_GP.pdf"), width = 6, height = 4, useDingbats = FALSE)
hist(gp_active_cell_counts, breaks = 100, xlab = "Number of highly active cells per GP", main = "Histogram of highly active cells per GP", freq = TRUE)
dev.off()

gp_active_cell_prop <- gp_active_cell_counts / nrow(L_pm_norm_col)
p_1E <- ggplot(data.frame(prop = gp_active_cell_prop), aes(x = prop)) +
  geom_histogram(bins = 40, fill = "steelblue", color = "white") +
  scale_x_log10(labels = scales::label_percent()) +
  annotation_logticks(sides = "b") +
  labs(x = "Proportion of highly active cells per GP (log scale)", y = "Count",
       title = "Histogram of highly active cells per GP (proportion)") +
  theme_minimal(base_size = 13)
ggsave(filename = paste0(figure_path, "1E.pdf"), plot = p_1E, width = 6, height = 4, dpi = 300)

cells_activated <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level2_group == "activated"]
L_pm_activated <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_activated, ]
gp_active_cell_counts_activated <- rowSums(L_pm_activated > 1e-1)
cells_resting <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level2_group == "resting"]
L_pm_resting <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_resting, ]
gp_active_cell_counts_resting <- rowSums(L_pm_resting > 1e-1)
gp_active_cell_counts_df <- data.frame(
  Group = c(rep("Activated", length(gp_active_cell_counts_activated)), rep("Resting", length(gp_active_cell_counts_resting))),
  Active_Cell_Counts = c(gp_active_cell_counts_activated, gp_active_cell_counts_resting)
)
p_1H <- ggplot(gp_active_cell_counts_df, aes(x = Group, y = Active_Cell_Counts, fill = Group)) +
  geom_boxplot(outlier.size = 0.4, width = 0.6, alpha = 0.8, color = "gray40") +
  scale_fill_manual(values = c("Activated" = "#1f78b4", "Resting" = "#e31a1c")) +
  labs(title = "", x = "", y = "Number of highly active GPs") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13, face = "bold"), legend.position = "none")
ggsave(filename = paste0(figure_path, "1H.pdf"), plot = p_1H, width = 6, height = 4, dpi = 300) # boxplot_active_cells_per_GP

gp_active_cell_counts_level1 <- dplyr::bind_rows(lapply(level1_order, function(grp) {
  cells_grp <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level1 == grp]
  L_grp <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_grp, , drop = FALSE]
  data.frame(Group = grp, Active_Cell_Counts = rowSums(L_grp > 1e-1))
}))
group_counts <- gp_active_cell_counts_level1 %>%
  group_by(Group) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(Group_Label = paste0(Group, "\n(n=", n, ")")) %>%
  mutate(Group = factor(Group, levels = level1_order)) %>%
  arrange(Group) %>%
  mutate(Group_Label = factor(Group_Label, levels = Group_Label))
plot_df_g <- gp_active_cell_counts_level1 %>% left_join(group_counts, by = "Group")
p_1G <- ggplot(plot_df_g, aes(x = Group_Label, y = Active_Cell_Counts, fill = Group)) +
  geom_boxplot(outlier.size = 0.4, width = 0.6, alpha = 0.8, color = "gray40") +
  scale_fill_manual(values = ZemmourLib::immgent_colors$level1) +
  labs(title = "Active Gene Programs per Group", x = "Cell Group (Annotation Level 1)", y = "Number of highly active GPs") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5), plot.subtitle = element_text(size = 11, color = "gray30", hjust = 0.5), axis.text.x = element_text(size = 11, angle = 45, hjust = 1), axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13, face = "bold"), legend.position = "none", panel.grid.minor = element_blank())
ggsave(filename = paste0(figure_path, "1G.pdf"), plot = p_1G, width = 6, height = 4, dpi = 300) # boxplot_active_cells_per_GP_level1

gp_active_cell_counts_all <- rowSums(L_pm_filtered > 1e-1)
gp_cd44_df <- data.frame(CD44_Protein_Level = protein_mat_normalized_lognorm, Active_GP_Counts = gp_active_cell_counts_all)
set.seed(123)
df_nz <- gp_cd44_df %>% dplyr::filter(CD44_Protein_Level > 0)
df_nz <- df_nz %>% sample_n(min(10000, nrow(df_nz)))
R <- cor(df_nz$CD44_Protein_Level, df_nz$Active_GP_Counts, use = "complete.obs")
p_1I <- ggplot(df_nz, aes(CD44_Protein_Level, Active_GP_Counts)) +
  geom_point(alpha = 0.1, size = 0.7) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(title = "CD44 Protein Level vs Number of Active GPs", x = "CD44 Protein Level (log-normalized)", y = "Number of Active GPs") +
  annotate("text", x = min(df_nz$CD44_Protein_Level, na.rm = TRUE) + 0.5, y = max(df_nz$Active_GP_Counts, na.rm = TRUE) - 1, label = paste0("R = ", round(R, 2)), size = 4) +
  theme_minimal(base_size = 13)
ggsave(filename = paste0(figure_path, "1I.pdf"), plot = p_1I, width = 6, height = 4, dpi = 300) # scatterplot_CD44_vs_active_GPs

F_pm_norm_col <- F_pm_filtered / matrix(apply(F_pm_filtered, 2, function(x) max(abs(x))), nrow = nrow(F_pm_filtered), ncol = ncol(F_pm_filtered), byrow = TRUE)
gp_active_gene_counts <- colSums(abs(F_pm_norm_col) > 0.25)
p_1F <- ggplot(data.frame(count = gp_active_gene_counts), aes(x = count)) +
  geom_histogram(bins = 40, fill = "steelblue", color = "white") +
  scale_x_log10(labels = scales::label_comma()) +
  annotation_logticks(sides = "b") +
  labs(x = "Number of highly active genes per GP (log scale)", y = "Count",
       title = "Histogram of highly active genes per GP") +
  theme_minimal(base_size = 13)
ggsave(filename = paste0(figure_path, "1F.pdf"), plot = p_1F, width = 6, height = 4, dpi = 300)

gp_active_gene_prop <- gp_active_gene_counts / nrow(F_pm_norm_col)
pdf(paste0(figure_path, "hist_active_genes_prop_per_GP.pdf"), width = 6, height = 4, useDingbats = FALSE)
hist(gp_active_gene_prop, breaks = 100, xlab = "Proportion of highly active genes per GP", main = "Histogram of highly active genes per GP (proportion)", freq = TRUE)
dev.off()

# ============================================================
# 1D: GP1 signature volcano (see code/R/volcano_helpers.R header
# for why this isn't from Figure_Overview.R)
# ============================================================
F_pm_filtered_1d <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
colnames(F_pm_filtered_1d) <- paste0("GP", seq_len(ncol(F_pm_filtered_1d)))
F_pm_normalized_1d <- normalize_maxabs(F_pm_filtered_1d)
mean_shifted_log_expr <- readRDS(paste0(data_path, "mean_shifted_log_expr.rds"))

p_1D <- plot_gp_signature_volcano("GP1", F_pm_normalized_1d, mean_shifted_log_expr, threshold = 0.1, n_label = 47, bg_alpha = 0.2)
ggsave(filename = paste0(figure_path, "1D.pdf"), plot = p_1D, width = 7, height = 5.5)

# ============================================================
# PVE-colored scatter of expected active-cell vs active-gene proportion
# (not one of the 9 lettered panels -- kept under its descriptive name)
# ============================================================
pve <- flashier_snmf_summary$pve
eps <- 0
pve_log <- log10(pve + eps)
pve_log_min <- quantile(pve_log, 0.02, na.rm = TRUE)
pve_log_max <- quantile(pve_log, 0.98, na.rm = TRUE)
pve_log_clipped <- pmin(pmax(pve_log, pve_log_min), pve_log_max)
pve_scaled <- (pve_log_clipped - min(pve_log_clipped)) / (max(pve_log_clipped) - min(pve_log_clipped))
n_col <- 100
pal <- colorRampPalette(c("lightgray", "skyblue", "darkblue"))(n_col)
idx_col <- pmin(pmax(1, floor(pve_scaled * (n_col - 1)) + 1), n_col)
col_points <- pal[idx_col]
load(paste0(data_path, "flashier_snmf_fitted_prior.rda"))
l_pi_vec <- sapply(1:200, function(i) flashier_snmf_fitted_prior$L_ghat[[i]]$pi[1])
f_pi_vec <- sapply(1:200, function(i) flashier_snmf_fitted_prior$F_ghat[[i]]$pi[1])
p_cells <- (1 - l_pi_vec)
p_genes <- (1 - f_pi_vec)

pdf(paste0(figure_path, "scatter_e_active_cells_vs_genes.pdf"), width = 6, height = 6)
plot(
  p_cells, p_genes,
  xlab = "Expected proportion of active cells", ylab = "Expected proportion of active genes",
  log = "xy", col = col_points, pch = 19, xaxt = "n", yaxt = "n",
  main = "Expected proportion of active cells vs genes per GP\n(colored by PVE)"
)
ticks <- c(0.0001, 0.001, 0.01, 0.05, 0.1, 0.3, 0.5, 1)
axis(1, at = ticks, labels = paste0(ticks * 100, "%"))
axis(2, at = ticks, labels = paste0(ticks * 100, "%"))
brks_pve <- c(1e-7, 1e-5, 1e-3, 1e-2, 0.1, 0.2)
brks_pve <- brks_pve[brks_pve >= min(pve) & brks_pve <= max(pve)]
brks_log <- log10(brks_pve + eps)
brks_log_clipped <- pmin(pmax(brks_log, pve_log_min), pve_log_max)
brks_scaled <- (brks_log_clipped - min(pve_log_clipped)) / (max(pve_log_clipped) - min(pve_log_clipped))
brks_idx <- pmin(pmax(1, floor(brks_scaled * (n_col - 1)) + 1), n_col)
brks_cols <- pal[brks_idx]
legend("bottomright", legend = format(brks_pve, scientific = TRUE, digits = 2), col = brks_cols, pch = 15, pt.cex = 1.5, title = "PVE", bty = "n")
dev.off()
