# Figure 1. Overview.
#
# Panels produced (final files figures/final-selected/bits/Figure 1/1A.pdf .. 1I.pdf;
# no separate caption file was found for Figure 1 during this refactor):
#   1A  Global MDE colored by major lineage (subsampled per lineage).
#   1B  Hand-finished schematic (Adobe Illustrator) -- NOT code-generated,
#       no source to port. Not produced by this script.
#   1C  Giant heatmap of all 200 GP loadings, cells stratified by lineage x organ.
#   1D  "Signature volcano" for GP1: each gene's normalized weight vs. mean
#       shifted-log expression, top genes labeled. NOT from the original
#       pre-refactor analysis code -- generated by the separate
#       "immgen-signature" Shiny app
#       (.../Immgen/webapps/immgen-signature/); see
#       code/R/volcano_helpers.R for the ported plotting function
#       and the caveat about n_label/threshold not being exactly recoverable.
#   1E  Histogram of the proportion of highly-active cells per GP.
#   1F  Histogram of the number of highly-active genes per GP.
#   1G  Boxplot of active-GP-count per cell, by major lineage.
#   1H  Boxplot of active-GP-count per cell, activated vs resting.
#   1I  Scatter of CD44 protein level vs. number of active GPs per cell.
# The original Figure_Overview.R produces 3 more outputs (raw
# active-cell-count histogram, active-gene proportion histogram, and a
# PVE-colored active-cell-vs-active-gene scatter) that don't match any
# remaining final-figure byte size -- saved under their descriptive names
# (not lettered) since they appear to not be part of the final 9-panel set.
#
# Source: ported from Figure_Overview.R (panels C, E-I) and
# Figure_Lineage.R's "MDE by Lineage" section (panel A, confirmed by
# an exact byte match between figures/final-selected/bits/Figure 1/1A.pdf
# and figures/Figure2_Lineage/UMAP_level1_group.pdf during this refactor).
#
# Required inputs (data/) -- see code/README.md's "Data provenance" table
# for the full picture:
#   flashier_snmf_summary.rds                [code/pipeline/01_extract_data.R]
#   L_pm_filtered.rds, F_pm_filtered.rds      [code/pipeline/01b_filter_cells.R]
#   igt1_96_..._ADTonly.Rds                   [primary input Seurat object]
#   protein_mat_normalized_lognorm.rds        [gap, no producer script here]
#   umap_result.rds                           [gap, no producer script here]
#   mean_shifted_log_expr.rds                 [gap, no producer script here]
#   flashier_snmf_fitted_prior.rda            [gap, no producer script here]

library(ggplot2)
library(dplyr)
library(scattermore)
library(ComplexHeatmap)
library(circlize)
library(tibble)
library(Matrix) # protein_mat_normalized_lognorm is a dgCMatrix; must be
                # attached (not just loaded) for `[` subsetting to dispatch

data_path <- "data/"
figure_path <- "figures/generated/Figure 1/"
source("code/R/volcano_helpers.R") # plot_gp_signature_volcano() for panel 1D

# ============================================================
# Load data
# ============================================================
flashier_snmf_summary <- readRDS(paste0(data_path, "flashier_snmf_summary.rds"))
L_pm_filtered <- readRDS(paste0(data_path, "L_pm_filtered.rds"))
F_pm_filtered <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
seurat_meta <- readRDS(paste0(data_path, "igt1_96_withtotalvi20260206_clean_ADTonly.Rds"))@meta.data
seurat_meta_filtered <- seurat_meta[rownames(L_pm_filtered), ]
protein_mat_normalized_lognorm <- readRDS(paste0(data_path, "protein_mat_normalized_lognorm.rds"))
protein_mat_normalized_lognorm <- protein_mat_normalized_lognorm[rownames(L_pm_filtered), "CD44"]
mde_result <- readRDS(paste0(data_path, "umap_result.rds"))
colnames(mde_result) <- c("MDE_1", "MDE_2")
mde_result <- mde_result[rownames(L_pm_filtered), ]
df_mde <- as.data.frame(mde_result)

# ============================================================
# 1A: Global MDE colored by major lineage, subsampled per lineage
# ============================================================
set.seed(1)
df_mde_a <- df_mde %>% tibble::rownames_to_column("cellID")
plot_df <- df_mde_a %>%
  inner_join(seurat_meta_filtered %>% select(cellID, annotation_level1), by = "cellID") %>%
  filter(annotation_level1 != "thymocyte")
max_total <- 1000000
min_per_group <- 300
cap_per_group <- 20000
group_sizes <- plot_df %>% count(annotation_level1, name = "n")
G <- nrow(group_sizes)
base_per_group <- ceiling(max_total / max(G, 1))
sample_plan <- group_sizes %>% mutate(n_take = pmin(n, pmax(min_per_group, pmin(cap_per_group, base_per_group))))
plot_df_sub <- plot_df %>%
  group_by(annotation_level1) %>%
  group_modify(~ dplyr::slice_sample(.x, n = sample_plan$n_take[sample_plan$annotation_level1 == .y$annotation_level1])) %>%
  ungroup()

p_1A <- ggplot(plot_df_sub, aes(x = MDE_1, y = MDE_2)) +
  scattermore::geom_scattermore(aes(color = annotation_level1), pointsize = 1.2) +
  scale_color_manual(values = ZemmourLib::immgent_colors$level1) +
  coord_equal() +
  theme_classic() +
  labs(title = "MDE: Annotation Level 1", x = "MDE 1", y = "MDE 2", color = "Cell Type") +
  theme(legend.text = element_text(size = 10), legend.key.size = unit(1.5, "lines")) +
  guides(color = guide_legend(override.aes = list(size = 4)))
ggsave(filename = paste0(figure_path, "1A.pdf"), plot = p_1A, width = 5, height = 5)

# 1B: hand-finished Illustrator schematic -- not code-generated, no output here.

# Drop thymocytes from all downstream cell-level visualizations (matches
# Figure_Overview.R).
non_thymo_cells <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level1 != "thymocyte"]
L_pm_filtered <- L_pm_filtered[non_thymo_cells, ]
seurat_meta_filtered <- seurat_meta_filtered[non_thymo_cells, ]
protein_mat_normalized_lognorm <- protein_mat_normalized_lognorm[non_thymo_cells]

# ============================================================
# 1C: giant heatmap of 200 GP loadings, cells stratified by lineage x organ
# ============================================================
set.seed(6173)
MIN_CELLS <- 20
N_SAMPLE <- 80
TOP_ORGANS <- 5
K_ANCHOR <- 5
level1_order <- c("CD8", "CD4", "Treg", "gdT", "CD8aa", "Tz", "DN")

organs_all <- as.character(unique(seurat_meta_filtered$organ_simplified))
ln_match <- organs_all[grepl("^LN$|lymph", organs_all, ignore.case = TRUE)]
spleen_match <- organs_all[grepl("spleen", organs_all, ignore.case = TRUE)]
other_organs <- sort(setdiff(organs_all, c(ln_match, spleen_match)))
organ_order <- c(spleen_match, ln_match, other_organs)

top_organ_combos <- seurat_meta_filtered |>
  dplyr::filter(annotation_level1 %in% level1_order) |>
  dplyr::count(annotation_level1, organ_simplified) |>
  dplyr::group_by(annotation_level1) |>
  dplyr::slice_max(n, n = TOP_ORGANS, with_ties = FALSE) |>
  dplyr::ungroup() |>
  dplyr::select(annotation_level1, organ_simplified)

sampled_random <- seurat_meta_filtered |>
  dplyr::filter(annotation_level1 %in% level1_order) |>
  dplyr::inner_join(top_organ_combos, by = c("annotation_level1", "organ_simplified")) |>
  dplyr::group_by(annotation_level1, organ_simplified) |>
  dplyr::filter(dplyr::n() >= MIN_CELLS) |>
  dplyr::slice_sample(n = N_SAMPLE) |>
  dplyr::ungroup()

anchor_cellids <- apply(L_pm_filtered, 2, function(x) {
  rownames(L_pm_filtered)[order(x, decreasing = TRUE)[seq_len(K_ANCHOR)]]
}) |> as.vector() |> unique()

anchor_meta <- seurat_meta_filtered |>
  dplyr::filter(cellID %in% anchor_cellids, annotation_level1 %in% level1_order) |>
  dplyr::inner_join(top_organ_combos, by = c("annotation_level1", "organ_simplified"))

all_meta <- dplyr::bind_rows(sampled_random, anchor_meta) |>
  dplyr::distinct(cellID, .keep_all = TRUE) |>
  dplyr::arrange(factor(annotation_level1, levels = level1_order), factor(organ_simplified, levels = organ_order))

L_sampled <- L_pm_filtered[all_meta$cellID, ]
clip_val <- quantile(L_sampled, 0.99)
L_display <- pmin(L_sampled, clip_val)
colnames(L_display) <- gsub("^K", "GP", colnames(L_display))

col_fun <- colorRamp2(c(0, clip_val / 2, clip_val), c("white", "#4393c3", "#08306b"))
level1_colors <- ZemmourLib::immgent_colors$level1
organ_colors <- ZemmourLib::immgent_colors$organ_simplified
level1_present <- intersect(level1_order, as.character(unique(all_meta$annotation_level1)))
organ_present <- intersect(organ_order, as.character(unique(all_meta$organ_simplified)))

row_ann <- rowAnnotation(
  Cell_Type = factor(as.character(all_meta$annotation_level1), levels = level1_present),
  Organ = factor(as.character(all_meta$organ_simplified), levels = organ_present),
  col = list(Cell_Type = level1_colors[level1_present], Organ = organ_colors[organ_present]),
  annotation_name_gp = gpar(fontsize = 8),
  annotation_legend_param = list(Cell_Type = list(title = "Cell Type"), Organ = list(title = "Organ"))
)

ht <- Heatmap(
  L_display, name = "Loading", col = col_fun, left_annotation = row_ann,
  cluster_rows = FALSE, cluster_columns = TRUE,
  clustering_distance_columns = "euclidean", clustering_method_columns = "ward.D2",
  show_row_names = FALSE, column_names_gp = gpar(fontsize = 4),
  column_title = "Gene Programs (GPs)", column_title_gp = gpar(fontsize = 11, fontface = "bold"),
  use_raster = TRUE, raster_quality = 3, border = FALSE,
  heatmap_legend_param = list(title = "Loading", direction = "vertical")
)
pdf(paste0(figure_path, "1C.pdf"), width = 15, height = 20, useDingbats = FALSE)
draw(ht, merge_legend = TRUE)
dev.off()

# ============================================================
# Candidates for 1D-1I: histograms of active-cell / active-gene counts
# (raw and proportion), boxplots of active-GP-count (activated vs resting;
# by lineage), CD44-vs-active-GP-count scatter, and the PVE-colored
# active-cell-vs-active-gene proportion scatter. 8 candidates, 6 final
# slots -- letters assigned by byte-size match against the ground truth
# during this refactor (see header note); unmatched two kept under their
# descriptive names.
# ============================================================
L_pm_norm_col <- L_pm_filtered / matrix(apply(L_pm_filtered, 2, function(x) max(x)), nrow = nrow(L_pm_filtered), ncol = ncol(L_pm_filtered), byrow = TRUE)
gp_active_cell_counts <- colSums((L_pm_norm_col) > 1e-1)

pdf(paste0(figure_path, "hist_active_cells_per_GP.pdf"), width = 6, height = 4, useDingbats = FALSE)
hist(gp_active_cell_counts, breaks = 100, xlab = "Number of highly active cells per GP", main = "Histogram of highly active cells per GP", freq = TRUE)
dev.off()

gp_active_cell_prop <- gp_active_cell_counts / nrow(L_pm_norm_col)
pdf(paste0(figure_path, "1E.pdf"), width = 6, height = 4, useDingbats = FALSE) # hist_active_cells_prop_per_GP
hist(gp_active_cell_prop, breaks = 100, xlab = "Proportion of highly active cells per GP", main = "Histogram of highly active cells per GP (proportion)", freq = TRUE)
dev.off()

cells_activated <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level2_group == "activated"]
L_pm_activated <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_activated, ]
gp_active_cell_counts_activated <- rowSums(L_pm_activated > 1e-1)
cells_resting <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level2_group == "resting"]
L_pm_resting <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_resting, ]
gp_active_cell_counts_resting <- rowSums(L_pm_resting > 1e-1)
gp_active_cell_counts_df <- data.frame(
  Group = c(rep("Activated", length(gp_active_cell_counts_activated)), rep("Resting", length(gp_active_cell_counts_resting))),
  Active_Cell_Counts = c(gp_active_cell_counts_activated, gp_active_cell_counts_resting)
)
p_1H <- ggplot(gp_active_cell_counts_df, aes(x = Group, y = Active_Cell_Counts, fill = Group)) +
  geom_boxplot(outlier.size = 0.4, width = 0.6, alpha = 0.8, color = "gray40") +
  scale_fill_manual(values = c("Activated" = "#1f78b4", "Resting" = "#e31a1c")) +
  labs(title = "", x = "", y = "Number of highly active GPs") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5), axis.text.x = element_text(size = 12), axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13, face = "bold"), legend.position = "none")
ggsave(filename = paste0(figure_path, "1H.pdf"), plot = p_1H, width = 6, height = 4, dpi = 300) # boxplot_active_cells_per_GP

gp_active_cell_counts_level1 <- dplyr::bind_rows(lapply(level1_order, function(grp) {
  cells_grp <- seurat_meta_filtered$cellID[seurat_meta_filtered$annotation_level1 == grp]
  L_grp <- L_pm_filtered[seurat_meta_filtered$cellID %in% cells_grp, , drop = FALSE]
  data.frame(Group = grp, Active_Cell_Counts = rowSums(L_grp > 1e-1))
}))
group_counts <- gp_active_cell_counts_level1 %>%
  group_by(Group) %>%
  summarise(n = n(), .groups = "drop") %>%
  mutate(Group_Label = paste0(Group, "\n(n=", n, ")")) %>%
  mutate(Group = factor(Group, levels = level1_order)) %>%
  arrange(Group) %>%
  mutate(Group_Label = factor(Group_Label, levels = Group_Label))
plot_df_g <- gp_active_cell_counts_level1 %>% left_join(group_counts, by = "Group")
p_1G <- ggplot(plot_df_g, aes(x = Group_Label, y = Active_Cell_Counts, fill = Group)) +
  geom_boxplot(outlier.size = 0.4, width = 0.6, alpha = 0.8, color = "gray40") +
  scale_fill_manual(values = ZemmourLib::immgent_colors$level1) +
  labs(title = "Active Gene Programs per Group", x = "Cell Group (Annotation Level 1)", y = "Number of highly active GPs") +
  theme_minimal(base_size = 13) +
  theme(plot.title = element_text(face = "bold", size = 14, hjust = 0.5), plot.subtitle = element_text(size = 11, color = "gray30", hjust = 0.5), axis.text.x = element_text(size = 11, angle = 45, hjust = 1), axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 13, face = "bold"), legend.position = "none", panel.grid.minor = element_blank())
ggsave(filename = paste0(figure_path, "1G.pdf"), plot = p_1G, width = 6, height = 4, dpi = 300) # boxplot_active_cells_per_GP_level1

gp_active_cell_counts_all <- rowSums(L_pm_filtered > 1e-1)
gp_cd44_df <- data.frame(CD44_Protein_Level = protein_mat_normalized_lognorm, Active_GP_Counts = gp_active_cell_counts_all)
set.seed(123)
df_nz <- gp_cd44_df %>% dplyr::filter(CD44_Protein_Level > 0)
df_nz <- df_nz %>% sample_n(min(10000, nrow(df_nz)))
R <- cor(df_nz$CD44_Protein_Level, df_nz$Active_GP_Counts, use = "complete.obs")
p_1I <- ggplot(df_nz, aes(CD44_Protein_Level, Active_GP_Counts)) +
  geom_point(alpha = 0.1, size = 0.7) +
  geom_smooth(method = "lm", se = TRUE) +
  labs(title = "CD44 Protein Level vs Number of Active GPs", x = "CD44 Protein Level (log-normalized)", y = "Number of Active GPs") +
  annotate("text", x = min(df_nz$CD44_Protein_Level, na.rm = TRUE) + 0.5, y = max(df_nz$Active_GP_Counts, na.rm = TRUE) - 1, label = paste0("R = ", round(R, 2)), size = 4) +
  theme_minimal(base_size = 13)
ggsave(filename = paste0(figure_path, "1I.pdf"), plot = p_1I, width = 6, height = 4, dpi = 300) # scatterplot_CD44_vs_active_GPs

F_pm_norm_col <- F_pm_filtered / matrix(apply(F_pm_filtered, 2, function(x) max(abs(x))), nrow = nrow(F_pm_filtered), ncol = ncol(F_pm_filtered), byrow = TRUE)
gp_active_gene_counts <- colSums(abs(F_pm_norm_col) > 0.25)
pdf(paste0(figure_path, "1F.pdf"), width = 6, height = 4, useDingbats = FALSE) # hist_active_genes_per_GP
hist(gp_active_gene_counts, breaks = 100, xlab = "Number of highly active genes per GP", main = "Histogram of highly active genes per GP", freq = TRUE)
dev.off()

gp_active_gene_prop <- gp_active_gene_counts / nrow(F_pm_norm_col)
pdf(paste0(figure_path, "hist_active_genes_prop_per_GP.pdf"), width = 6, height = 4, useDingbats = FALSE)
hist(gp_active_gene_prop, breaks = 100, xlab = "Proportion of highly active genes per GP", main = "Histogram of highly active genes per GP (proportion)", freq = TRUE)
dev.off()

# ============================================================
# 1D: GP1 signature volcano (see code/R/volcano_helpers.R header
# for why this isn't from Figure_Overview.R)
# ============================================================
F_pm_filtered_1d <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
colnames(F_pm_filtered_1d) <- paste0("GP", seq_len(ncol(F_pm_filtered_1d)))
F_pm_normalized_1d <- normalize_maxabs(F_pm_filtered_1d)
mean_shifted_log_expr <- readRDS(paste0(data_path, "mean_shifted_log_expr.rds"))

p_1D <- plot_gp_signature_volcano("GP1", F_pm_normalized_1d, mean_shifted_log_expr, threshold = 0.1, n_label = 47, bg_alpha = 0.2)
ggsave(filename = paste0(figure_path, "1D.pdf"), plot = p_1D, width = 7, height = 5.5)

# ============================================================
# PVE-colored scatter of expected active-cell vs active-gene proportion
# (not one of the 9 lettered panels -- kept under its descriptive name)
# ============================================================
pve <- flashier_snmf_summary$pve
eps <- 0
pve_log <- log10(pve + eps)
pve_log_min <- quantile(pve_log, 0.02, na.rm = TRUE)
pve_log_max <- quantile(pve_log, 0.98, na.rm = TRUE)
pve_log_clipped <- pmin(pmax(pve_log, pve_log_min), pve_log_max)
pve_scaled <- (pve_log_clipped - min(pve_log_clipped)) / (max(pve_log_clipped) - min(pve_log_clipped))
n_col <- 100
pal <- colorRampPalette(c("lightgray", "skyblue", "darkblue"))(n_col)
idx_col <- pmin(pmax(1, floor(pve_scaled * (n_col - 1)) + 1), n_col)
col_points <- pal[idx_col]
load(paste0(data_path, "flashier_snmf_fitted_prior.rda"))
l_pi_vec <- sapply(1:200, function(i) flashier_snmf_fitted_prior$L_ghat[[i]]$pi[1])
f_pi_vec <- sapply(1:200, function(i) flashier_snmf_fitted_prior$F_ghat[[i]]$pi[1])
p_cells <- (1 - l_pi_vec)
p_genes <- (1 - f_pi_vec)

pdf(paste0(figure_path, "scatter_e_active_cells_vs_genes.pdf"), width = 6, height = 6)
plot(
  p_cells, p_genes,
  xlab = "Expected proportion of active cells", ylab = "Expected proportion of active genes",
  log = "xy", col = col_points, pch = 19, xaxt = "n", yaxt = "n",
  main = "Expected proportion of active cells vs genes per GP\n(colored by PVE)"
)
ticks <- c(0.0001, 0.001, 0.01, 0.05, 0.1, 0.3, 0.5, 1)
axis(1, at = ticks, labels = paste0(ticks * 100, "%"))
axis(2, at = ticks, labels = paste0(ticks * 100, "%"))
brks_pve <- c(1e-7, 1e-5, 1e-3, 1e-2, 0.1, 0.2)
brks_pve <- brks_pve[brks_pve >= min(pve) & brks_pve <= max(pve)]
brks_log <- log10(brks_pve + eps)
brks_log_clipped <- pmin(pmax(brks_log, pve_log_min), pve_log_max)
brks_scaled <- (brks_log_clipped - min(pve_log_clipped)) / (max(pve_log_clipped) - min(pve_log_clipped))
brks_idx <- pmin(pmax(1, floor(brks_scaled * (n_col - 1)) + 1), n_col)
brks_cols <- pal[brks_idx]
legend("bottomright", legend = format(brks_pve, scientific = TRUE, digits = 2), col = brks_cols, pch = 15, pt.cex = 1.5, title = "PVE", bty = "n")
dev.off()
