# Figure 2. GPs and lineages.
#
# Panels produced (see figures/final-selected/bits/Figure 2/Figure2_caption.md
# for the full caption text):
#   2A  Swarm plot of per-GP AUC (predicting major lineage), up-regulated
#       GPs only, with GP3/22/29 force-highlighted.
#   2B  Structure plot of 6 lineage-defining GPs across major lineages.
#   2C,2E,2G  GP loading on the global MDE, for GP68, GP30, GP58.
#   2D,2F,2H  Per-gene view (score vs. mean expression) for GP68, GP30, GP58.
#   2I  MDE restricted to gdT/CD8aa/DN, colored by lineage.
#   2J,2K,2L  GP loading on the gdT/CD8aa/DN MDE, for GP22, GP29, GP3.
#   2M  Heatmap of top-30 gene scores for GP3, GP22, GP29.
#
# Source: ported from Figure_Lineage.R, which also produced the
# Figure S2 panels (see FigureS2.R) from the same L_pm_filtered/MDE setup.
#
# Panels 2C/2E/2G (GP68/30/58 on the *global* MDE) have no direct
# equivalent in the original script -- Figure_Lineage.R only plots
# GP68/30/58-defined structure/boxplots, never their global-MDE loading.
# Reconstructed here with the same plot_loadings_on_mde() styling used for
# panels 2J/2K/2L (the closest in-script precedent).
#
# Panels 2D/2F/2H and 2M are NOT from the original pre-refactor analysis
# code at all -- they're generated by the separate "immgen-signature"
# Shiny app (see code/R/volcano_helpers.R and code/R/cross_gp_helpers.R
# headers for the full provenance notes).
#
# Required inputs (data/) -- see code/README.md's "Data provenance" table
# for the full picture:
#   igt1_96_..._ADTonly.Rds                  [primary input Seurat object]
#   L_pm_filtered.rds, F_pm_filtered.rds     [code/pipeline/01b_filter_cells.R]
#   umap_result.rds                          [gap, no producer script here]
#   level_1_AUC_list_figure_no_thymocytes_healthy.rds [code/pipeline/02_compute_auc.R]
#   mean_shifted_log_expr.rds                [gap, no producer script here]

library(ggplot2)
library(ggrepel)
library(dplyr)
library(tidyr)
library(tibble)
library(scattermore)
library(pheatmap)
library(fastTopics) # structure_plot()

data_path <- "data/"
figure_path <- "figures/generated/Figure 2/"
source("code/R/plot_utils.R") # lineage_colors()
source("code/R/lineage_plots.R") # plot_gp_swarm(), plot_loadings_on_mde()
source("code/R/volcano_helpers.R") # plot_gp_signature_volcano(), normalize_maxabs()
source("code/R/cross_gp_helpers.R") # plot_cross_gp_heatmap()

# ============================================================
# Load data
# ============================================================
seurat_meta <- readRDS(paste0(
  data_path,
  "igt1_96_withtotalvi20260206_clean_ADTonly.Rds"
))@meta.data
L_pm_filtered <- readRDS(paste0(data_path, "L_pm_filtered.rds"))
seurat_meta_filtered <- seurat_meta[rownames(L_pm_filtered), ]
mde_result <- readRDS(paste0(data_path, "umap_result.rds"))
colnames(mde_result) <- c("MDE_1", "MDE_2")
mde_result <- mde_result[rownames(L_pm_filtered), ]
df_mde <- as.data.frame(mde_result)
level_1_AUC_list <- readRDS(paste0(data_path, "level_1_AUC_list_figure_no_thymocytes_healthy.rds"))

# Rename K## to GP## for display consistency
colnames(L_pm_filtered) <- gsub("^K", "GP", colnames(L_pm_filtered))
colnames(level_1_AUC_list$auc) <- gsub(
  "^K",
  "GP",
  colnames(level_1_AUC_list$auc)
)

# ============================================================
# 2A: AUC swarm, up-regulated GPs only, GP3/22/29 forced highlight
# ============================================================
selected_lineage_in_order <- c("CD8", "CD4", "Treg", "gdT", "CD8aa", "Tz", "DN")
level_1_categories <- as.character(unique(
  seurat_meta_filtered$annotation_level1
))

mean_loading_matrix <- t(sapply(level_1_categories, function(cat) {
  cells_in_cat <- which(seurat_meta_filtered$annotation_level1 == cat)
  colMeans(L_pm_filtered[cells_in_cat, , drop = FALSE], na.rm = TRUE)
}))
mean_loading_matrix_selected <- mean_loading_matrix[selected_lineage_in_order, ]

non_thymocyte_cells <- which(
  seurat_meta_filtered$annotation_level1 != "thymocyte"
)
mean_loading_vec <- colMeans(
  L_pm_filtered[non_thymocyte_cells, , drop = FALSE],
  na.rm = TRUE
)

AUC_mat_selected <- level_1_AUC_list$auc[selected_lineage_in_order, ]

p_2A <- plot_gp_swarm(
  AUC_mat_selected,
  loading_mat = mean_loading_matrix,
  overall_loading_vec = mean_loading_vec,
  filter_positive = TRUE,
  forced_highlights = list(
    gdT = c("GP22", "GP29", "GP3"),
    CD8aa = c("GP22", "GP29", "GP3"),
    DN = c("GP22", "GP29", "GP3")
  ),
  top_k_labels = 1,
  threshold_line = 0.5,
  title = "Up-regulated GP Predictive Performance (AUC)",
  subtitle = "Up-regulated GPs (Loading >= Overall Mean); triangles mark forced highlights that are down-regulated",
  y_label = "Area Under the Curve (AUC)",
  italic_subtitle = TRUE
)
ggsave(
  filename = paste0(figure_path, "2A.pdf"),
  plot = p_2A,
  width = 10,
  height = 6
)

# ============================================================
# 2B: Structure plot of 6 lineage-defining GPs
# ============================================================
set.seed(1234)
color_coding <- ZemmourLib::immgent_colors$level1
level1_category_to_factor <- c(
  "Treg" = "GP68",
  "CD8" = "GP58",
  "Tz" = "GP30",
  "DN" = "GP22",
  "CD8aa" = "GP29",
  "gdT" = "GP3"
)
fit2 <- L_pm_filtered[, level1_category_to_factor, drop = FALSE]
cell_type <- seurat_meta[rownames(fit2), "annotation_level1"]
cells <- which(cell_type == "CD4" | cell_type == "CD8")
cells <- sample(cells, 1e5)
cells <- sort(c(
  cells,
  which(
    cell_type != "CD4" &
      cell_type != "CD8" &
      cell_type != "thymocyte" &
      cell_type != "DP"
  )
))

p_2B <- structure_plot(
  fit2[cells, ],
  gap = 40,
  n = 10000,
  colors = color_coding[names(level1_category_to_factor)],
  grouping = cell_type[cells]
) +
  labs(y = "membership", color = "", fill = "") +
  guides(fill = guide_legend(nrow = 1), color = guide_legend(nrow = 1)) +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    legend.box = "horizontal",
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 12),
    axis.title = element_text(size = 14, face = "bold"),
    legend.text = element_text(size = 12),
    legend.title = element_text(size = 13)
  )
ggsave(
  filename = paste0(figure_path, "2B.pdf"),
  plot = p_2B,
  width = 10,
  height = 6,
  dpi = 300
)

# ============================================================
# 2C/2E/2G: GP68, GP30, GP58 loading on the global MDE (reconstructed)
# ============================================================
p_2C <- plot_loadings_on_mde(
  mde = df_mde,
  loading = L_pm_filtered[rownames(df_mde), "GP68"],
  factor_num = 68,
  size = 0.6,
  bg_alpha = 0.1,
  bg_color = "grey90"
)
ggsave(
  filename = paste0(figure_path, "2C.pdf"),
  plot = p_2C,
  width = 5,
  height = 4
)

p_2E <- plot_loadings_on_mde(
  mde = df_mde,
  loading = L_pm_filtered[rownames(df_mde), "GP30"],
  factor_num = 30,
  size = 0.6,
  bg_alpha = 0.1,
  bg_color = "grey90"
)
ggsave(
  filename = paste0(figure_path, "2E.pdf"),
  plot = p_2E,
  width = 5,
  height = 4
)

p_2G <- plot_loadings_on_mde(
  mde = df_mde,
  loading = L_pm_filtered[rownames(df_mde), "GP58"],
  factor_num = 58,
  size = 0.6,
  bg_alpha = 0.1,
  bg_color = "grey90"
)
ggsave(
  filename = paste0(figure_path, "2G.pdf"),
  plot = p_2G,
  width = 5,
  height = 4
)

# ============================================================
# 2D/2F/2H: "signature volcano" per-gene view for GP68, GP30, GP58.
# NOT from the original pre-refactor analysis code -- generated by the
# separate "immgen-signature" Shiny app (see code/R/volcano_helpers.R header). n_label was
# bisected per-GP against the published PDF's byte size (apparently tuned
# per-panel interactively in the app); GP68 matches exactly, GP30/GP58
# within ~10 bytes.
# ============================================================
F_pm_filtered_2d <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
colnames(F_pm_filtered_2d) <- paste0("GP", seq_len(ncol(F_pm_filtered_2d)))
F_pm_normalized_2d <- normalize_maxabs(F_pm_filtered_2d)
mean_shifted_log_expr <- readRDS(paste0(data_path, "mean_shifted_log_expr.rds"))

p_2D <- plot_gp_signature_volcano(
  "GP68",
  F_pm_normalized_2d,
  mean_shifted_log_expr,
  threshold = 0.1,
  n_label = 100,
  bg_alpha = 0.2
)
ggsave(
  filename = paste0(figure_path, "2D.pdf"),
  plot = p_2D,
  width = 7,
  height = 5.5
)

p_2F <- plot_gp_signature_volcano(
  "GP30",
  F_pm_normalized_2d,
  mean_shifted_log_expr,
  threshold = 0.1,
  n_label = 100,
  bg_alpha = 0.2
)
ggsave(
  filename = paste0(figure_path, "2F.pdf"),
  plot = p_2F,
  width = 7,
  height = 5.5
)

p_2H <- plot_gp_signature_volcano(
  "GP58",
  F_pm_normalized_2d,
  mean_shifted_log_expr,
  threshold = 0.1,
  n_label = 83,
  bg_alpha = 0.2
)
ggsave(
  filename = paste0(figure_path, "2H.pdf"),
  plot = p_2H,
  width = 7,
  height = 5.5
)

# ============================================================
# 2I: MDE restricted to gdT/CD8aa/DN, colored by lineage
#     (excludes proliferating / miniverse subsets)
# ============================================================
gcd_lineages <- c("gdT", "CD8aa", "DN")
gcd_cells <- seurat_meta_filtered$cellID[
  seurat_meta_filtered$annotation_level1 %in%
    gcd_lineages &
    !(seurat_meta_filtered$annotation_level2_group %in%
      c("proliferating", "miniverse"))
]
df_mde_gcd <- df_mde[gcd_cells, ]
df_mde_gcd$annotation_level1 <- factor(
  seurat_meta_filtered[gcd_cells, "annotation_level1"],
  levels = gcd_lineages
)

p_2I <- ggplot(df_mde_gcd, aes(x = MDE_1, y = MDE_2)) +
  scattermore::geom_scattermore(
    aes(color = annotation_level1),
    pointsize = 1.2
  ) +
  scale_color_manual(values = lineage_colors()[gcd_lineages]) +
  coord_equal() +
  theme_classic() +
  labs(
    title = "MDE: gdT / CD8aa / DN",
    x = "MDE 1",
    y = "MDE 2",
    color = "Cell Type"
  ) +
  theme(
    legend.text = element_text(size = 10),
    legend.key.size = unit(1.5, "lines")
  ) +
  guides(color = guide_legend(override.aes = list(size = 4)))
ggsave(
  filename = paste0(figure_path, "2I.pdf"),
  plot = p_2I,
  width = 5,
  height = 5
)

# ============================================================
# 2J/2K/2L: GP22, GP29, GP3 loading on the gdT/CD8aa/DN MDE
# ============================================================
gp_letter <- c("GP22" = "2J", "GP29" = "2K", "GP3" = "2L")
for (gp_name in names(gp_letter)) {
  gp_num <- as.numeric(sub("^GP", "", gp_name))
  p_loading <- plot_loadings_on_mde(
    mde = df_mde_gcd[, c("MDE_1", "MDE_2")],
    loading = L_pm_filtered[gcd_cells, gp_name],
    factor_num = gp_num,
    size = 0.6,
    bg_alpha = 0.1,
    bg_color = "grey90"
  )
  ggsave(
    filename = paste0(figure_path, gp_letter[gp_name], ".pdf"),
    plot = p_loading,
    width = 5,
    height = 4
  )
}

# ============================================================
# 2M: cross-GP heatmap, top-30 gene weights for GP3, GP29, GP22
# (immgen-signature app's mod_cross_gp.R heatmap mode; see
# code/R/cross_gp_helpers.R)
#
# Column order (GP3, GP29, GP22) and pinning Fcer1g/Ccl5/Cd7 to the top 3
# rows are our own editorial choices, made after the app-faithful version
# (GP3, GP22, GP29; rows purely hclust-ordered) -- see plot_cross_gp_heatmap()'s
# `pin_top` argument. This means 2M is no longer a byte-exact reproduction
# of the published PDF (see script/README.md).
# ============================================================
F_pm_filtered_2m <- readRDS(paste0(data_path, "F_pm_filtered.rds"))
colnames(F_pm_filtered_2m) <- paste0("GP", seq_len(ncol(F_pm_filtered_2m)))
F_pm_norm_2m <- normalize_maxabs(F_pm_filtered_2m)
common_genes_2m <- intersect(rownames(F_pm_norm_2m), names(mean_shifted_log_expr))

gps_2m <- c("GP3", "GP29", "GP22")
mat_2m <- F_pm_norm_2m[common_genes_2m, gps_2m, drop = FALSE]

p_2M <- plot_cross_gp_heatmap(
  mat_2m, gps_2m,
  feat_label = "Gene", n_genes = 30, direction = "both",
  threshold = 0.05, colorscheme = "bwr", cluster_r = TRUE, cluster_c = FALSE,
  pin_top = c("Fcer1g", "Ccl5", "Cd7")
)
ph_2m <- max(4, 2 + 30 * 0.14)
pw_2m <- max(5, 3 + length(gps_2m) * 0.8)
ggsave(filename = paste0(figure_path, "2M.pdf"), plot = p_2M, width = pw_2m, height = ph_2m)
