---
title: "Extended Data Table 1: GP characteristics and annotations"
author: "Ziang Zhang"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

Produced by
[`script/ExtendedDataTable1_GP_summary.R`](https://github.com/AgueroZZ/immgenT-GP-analysis/blob/main/script/ExtendedDataTable1_GP_summary.R):

```{r edt1-code, code=readLines("../script/ExtendedDataTable1_GP_summary.R"), eval=FALSE}
```

## Table {#edt1}

Download: [`ExtendedDataTable1_GP_summary.xlsx`](https://github.com/AgueroZZ/immgenT-GP-analysis/raw/main/figures/final-selected/ExtendedDataTable1_GP_summary.xlsx).

```{r edt1-preview, echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(DT))
source("../code/R/table_xlsx.R")
tab <- read_table_xlsx("../figures/final-selected/ExtendedDataTable1_GP_summary.xlsx")
DT::datatable(
  tab,
  rownames = FALSE,
  filter = "top",
  options = list(
    pageLength = 10,
    lengthMenu = list(c(10, 25, 50, 100, -1), c("10", "25", "50", "100", "All")),
    scrollX = TRUE
  )
) |> DT::formatRound(columns = "Prop. active cells", digits = 4)
```

::: {.figcaption}
**Extended Data Table 1.** Characteristics of the 200 GPs: the columns show
the top 15 up- and down-regulated genes with |score| > 0.1, the proportion of
highly active cells (scaled loading > 0.1), and the number of highly active
genes (|score| > 0.25).
:::
