---
title: "Extended Data Table 3: GP association with lineages"
author: "Ziang Zhang"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

Produced by
[`script/ExtendedDataTable3_GP_AUC_lineage.R`](https://github.com/AgueroZZ/immgenT-GP-analysis/blob/main/script/ExtendedDataTable3_GP_AUC_lineage.R):

```{r edt3-code, code=readLines("../script/ExtendedDataTable3_GP_AUC_lineage.R"), eval=FALSE}
```

## Table {#edt3}

All 200 rows are browsable below: sort by clicking a column header, type a GP
name into the search box under the **GP** column, or use a per-lineage box to
filter by AUC range. Download the workbook at
[`figures/final-selected/ExtendedDataTable3_GP_AUC_lineage.xlsx`](https://github.com/AgueroZZ/immgenT-GP-analysis/raw/main/figures/final-selected/ExtendedDataTable3_GP_AUC_lineage.xlsx).

```{r edt3-preview, echo=FALSE, message=FALSE}
suppressPackageStartupMessages(library(DT))
source("../code/R/table_xlsx.R")
tab <- read_table_xlsx("../figures/final-selected/ExtendedDataTable3_GP_AUC_lineage.xlsx")
DT::datatable(
  tab,
  rownames = FALSE,
  filter = "top",
  options = list(
    pageLength = 10,
    lengthMenu = list(c(10, 25, 50, 100, -1), c("10", "25", "50", "100", "All")),
    scrollX = TRUE
  )
) |> DT::formatRound(columns = colnames(tab)[-1], digits = 3)
```

::: {.figcaption}
**Extended Data Table 3.** AUC score separating cells of each lineage from all
others using GP loadings (computed in cells at baseline).
:::
